### ISSUE TITLE
您好，在这里我也遇到了同样的问题，为什么pub窗口内第一帧的位姿呢

### ISSUE THREAD

**Issue by RuizhiChang** [narutojxl/lili_om_noted#1]
https://github.com/narutojxl/lili_om_noted/blob/c76bf2f413f70c03885cd83bd501cefba66d57e3/LiLi-OM-ROT/src/BackendFusion.cpp#L2393-L2404

**Comment by narutojxl** [comment]
Hello @ToutDonner,  I'm so sorry, as it's been a long time, I don't have the impression about this issue. I remeber i have the same issue when reading the code in the author raw repo, [https://github.com/KIT-ISAS/lili-om/issues/8](https://github.com/KIT-ISAS/lili-om/issues/8), you can discuss with him. Maybe because I asked some long-winded questions at the time, the author has blocked me,  so I can not continue to do anything about  that repo, including [https://github.com/KIT-ISAS/lili-om/issues/8](https://github.com/KIT-ISAS/lili-om/issues/8) and the remaining unconfirmed problems [https://github.com/KIT-ISAS/lili-om/issues/7](https://github.com/KIT-ISAS/lili-om/issues/7), if you have some ideas please continue to disscuss with author :)

**Comment by RuizhiChang** [comment]
Think for your reply! I just saw your issue, so I wanted to ask if you solved it ,lol.I will try to contact  the author.
